### ISSUE TITLE
Create "Developer Guide" out of existing content

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1261]
We would like to introduce a developer guide that would help those who create extensions and integration services for Keptn. 

## Scope

The developer guide would include:

Part 1. Developing integrations

- [ ] Introduction to Keptn development. "What if I need a new Keptn integration? How do I select a way to do it (service, webhook, JES)?"
- [ ] Developer environment setup guide
- [ ] Guides for creating integration services using standard service templates (Golang, Python). These guides can reside run in the repositories of the templates
- [ ] Guide for creating Job Executor Service images
- [ ] Guide for developing and testing new Webhook integrations
- [ ] Creating documentation for your integration. Best practices and how to get it published?
- [ ] Publishing your integration on ArtifactHub
- [ ] Creating a Killercoda tutorial for your integrations
- [ ] Maintaining your integration. Best practices, tips&tricks

Part 2. Developing Keptn Core

- [ ] How to? Sourced right from the Keptn Core repository, including CONTRIBUTING.md
- [ ] How to contribute changes?

## TODOs

- [ ] KEP for the developer guide documentation structure, targeting the new docs engine
- [ ] Create new documentation structure
- [ ] Rework existing content
- [ ] Create new content

## Depends on

- #994 

## Related issues

- https://github.com/keptn/keptn.github.io/issues/981

**Comment by DavidPHirsch** [comment]
outdated
