### ISSUE TITLE
Simplify installation - Do not install Istio nor NGNIX-ingress

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#576]
* Update docs for installation with the preferred service-type for each Cloud Provider: Each platform has different ways of using the service types NodePort and LoadBalancer, but we can tackle this with recommending the preferred option for the respective platform (e.g., GKE, AKS, EKS – Loadbalancer; MiniKube, K3s, MicroK8s: NodePort; OpenShift, MiniShift: ???)

* Document how to expose Keptn Bridge and API using service-type LoadBalancer or NodePort

* If the user wants to use an ingress-controller (e.g., nginx-ingress, istio, traefik) for API/Bridge, the recommended way is to use ClusterIP and apply an ingress manifest manually.

* Update docs for installation with a troubleshooting guide if API can not be reached (e.g., refer to Kubernetes services and description of ClusterIP vs. NodePort vs. LoadBalancer)

* Remove the experimental tutorial about reusing an existing ingress-gateway (e.g., Istio)

**Tasks**
* Provide a visual to explain the install process

* Implement the install guide according to the process

**Definition of Done**
- [ ] keptn.sh/docs/develop/operate/install/ provides an install guide as outlined above
- [ ] Double-check docs/develop for used `keptn install` commands: `quickstart`, `k8s_support`
- [ ] `Keptn with pre-installed Istio/NGINX (experimental)` removed
