### ISSUE TITLE
Check and fix 0.8.x docs for all CloudEvents and API calls

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#667]
Due to the upgrade of the CloudEvents from v0.2 to v1.0, the CloudEvent examples in the documentation have changed, e.g., the property "specversion": "1.0", "type"

First, take a look at real CloudEvent examples sent out by Keptn.

**Task**
- [ ] Review of all pages in 0.8.x in regard to the used CloudEvent examples → update of the examples to be v1.0 compliant
- [ ] Double-check of API call to the `/event` endpoint
- [ ] Double-check the link to the https://github.com/keptn/spec/blob/master/cloudevents.md file 
  - Do a search and replace of: `github.com/keptn/spec` links
