### ISSUE TITLE
New Documentation Site Engine

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#994]
The current website version is pretty weak when it comes to maintaining multiple versions of the documentation like we have now. It requires a lot of copy paste and we don't want her to maintain that going forward. IMHO we should introduce a new engine which allows to...

- Support for the `latest` link pointing to the documentation for the last release
- Use versioned documentation from external sources, ideally from version tags and branches
- Move documentation sources to code repositories so that we could enable documentation as code and make documentation patches a part of the contribution process
- TBD: Switch to Asciidoctor which is more flexible for production grade documentation thanks to native support of macros and other complex features not available in vanilla markdown

## Possible solutions

I would suggest considering [Antora](https://antora.org/) that is specifically designed for managing documentation at scale. The biggest problem is that it targets Asciidoctor, and the support ofor Markdown is not perfect. It will require some migration automation, e.g. with help of Pandoc.

Another solution would be to use Docusaurus as suggested by @iamrajiv in the GSoC project idea.

## Scope

- [ ] Creating a prototype, together with the community members
  * https://github.com/keptn-sandbox/new-keptn-docs-engine 
- [ ] Designing the structure of the desired site, most likely as a [Keptn Enhancement Proposal](https://github.com/keptn/enhancement-proposals/)
- [ ] Implementing automation that builds the site: Scripting and GitHub Actions
- [ ] Implement continuous delivery for the website
- [ ] Nice2have: Implement previews for the website and support for staging changes (e.g. pre-release documentation)

**Comment by johannes-b** [comment]
We started to discuss this topic also on this issue: https://github.com/keptn/keptn/issues/4980

**Comment by StackScribe** [comment]
I agree that we should consider using Antora and switching to asciidoctor for our source format.  asciidoctor is much more powerful, especially for internal xrefs and is not much more difficult to code than markdown

**Comment by j-poecher** [comment]
Using a tool like **asciidoctor** would also enable us to store all snippets and commands used in our tutorials in files. This could simplify the "extraction" process for "integration tests" - so e.g. you update the tutorial and the pipeline would setup an environment and run all the steps (i.e. all collected scripts including some **pre** or **post** actions/scripts before or after each step) of the tutorial automatically to verify that it actually still works after updating. *Just thinking out loud here...*

**Comment by iamrajiv** [comment]
Hi, @oleg-nenashev I want to work on this issue in GSoC 2022. I will suggest using [Docusaurus](https://docusaurus.io/) like it is more powerful than [Antora](https://antora.org/). It's an optimized site generator in React. Docusaurus helps you to move fast and write content. Build documentation websites, blogs, marketing pages, and more.

Should I make proof of concept for both Antora](https://antora.org/) and [Docusaurus](https://docusaurus.io/)?

**Comment by Biki-das** [comment]
I would like to work on this

**Comment by Mostafa-wael** [comment]
I would like to work on this project for GSOC 22

**Comment by StackScribe** [comment]
I drafted a requirements document that we can use to evaluate the new doc build tools: https://docs.google.com/document/d/1CVtDCOY3hc7j3-kCHh5lpkmGGF2Yc3sp-0FP5ExD_pk/edit# .  Please critique/augment.

**Comment by StackScribe** [comment]
See https://github.com/keptn-sandbox/new-keptn-docs-engine/issues/2 for progress

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
